version: '2'

services:
    node:
        image: node-server:latest
        volumes:
            - .:/app
        deploy:
            mode: replicated
            replicas: 5

    nginx:
        image: nginx:1.23.1
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - node

    graphite:
        image: graphiteapp/graphite-statsd:1.1.10-3
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    graphite_node:
        image: graphiteapp/graphite-statsd:1.1.10-3
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8091:80"
            - "8127:8125/udp"
            - "8128:8126"

    grafana:
        image: grafana/grafana:9.1.2
        ports:
            - "80:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.45.0
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="10s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

    bbox:
        image: arqsoft/bbox:202202.1
        volumes:
            - "./config.properties/:/opt/bbox/config.properties:ro"

volumes:
    grafana_config:
        driver: local
